### ISSUE TITLE
No support for sister languages?

### ISSUE THREAD

**Issue by phathoang** [snowflakeproductionsgmbh/snowbabel#16]
We use both Portuguese and Brazilian Portuguese in our installation. For Brazilian Portuguese we set config.language = pt_BR so we need an l10n/pt_BR folder for the translations. But adding Brazilian Portuguese to Snowbabel languages and using the Translation module only writes to the pt folder and not pt_BR.
Any solutions for this?

**Comment by WebsiteDeveloper** [comment]
Duplicate too #24
