### ISSUE TITLE
Does not use the right language key

### ISSUE THREAD

**Issue by megamisan** [snowflakeproductionsgmbh/snowbabel#17]
The extension use lg_iso2 for language key instead of lg_typo3.
TYPO3 use in all place an internal language key which match mostly to the iso2 key. There are a few exception like Traditional Chinese and Simplified Chinese which have the same iso2 code (zh) but two TYPO3 code (zh and ch).
It makes snowbabel put the files in the wrong place with the wrong name and unable to differentiate the two.

I have attached the simple patch. One liner.

[snowbabel_languagekey.patch.txt](https://github.com/snowflakech/snowbabel/files/108324/snowbabel_languagekey.patch.txt)

**Comment by WebsiteDeveloper** [comment]
Related to #24

**Comment by WebsiteDeveloper** [comment]
See Resolution of #24
