### ISSUE TITLE
Not compatible with TYPO3 7.6 LTS?

### ISSUE THREAD

**Issue by CDRO** [snowflakeproductionsgmbh/snowbabel#18]
Is it planned to release a 7.6 version of this cool extension?

I think it would be a shame to lose such a great tool to time :-(

**Comment by vertexvaar** [comment]
/push
I'm also interested

**Comment by dp-michaelhuebe** [comment]
Me too!

**Comment by vandres** [comment]
dito

**Comment by hojaonline** [comment]
We Fixed the compatibility issues in 7.6. Final QA is going on new supported version will be released soon.

**Comment by vandres** [comment]
@hojaonline any news?

**Comment by pitsolutionstypo3** [comment]
@vandres New Version 5.0 is releases in TER. Cheers :)

**Comment by vandres** [comment]
@pitsolutionstypo3 Thanks!

**Comment by beardcoder** [comment]
At the moment v5 do not work with 7 LTS. Settingsmanager write wrong settings to the LocalConfig.
This is why the translation module does not work.

**Comment by rickymathew** [comment]
The issue with translation module has been fixed.
