### ISSUE TITLE
Please register on packagist.org

### ISSUE THREAD

**Issue by vertexvaar** [snowflakeproductionsgmbh/snowbabel#19]
Hi there,

it would be really nice if you could register this extension on https://packagist.org, so people are able to require it simply via composer. That saves a lot of time for everyone, the registration is very simple and requires no further administration once the service integration was made.

Helmut has published a very detailed example how to write a good composer.json in his scaffold extension: https://github.com/helhum/ext_scaffold/blob/master/composer.json
All of that stiff is explained in that extension, too.

With regards and thanks in advance

**Comment by romm** [comment]
Bump! 

Would really like to see it on Packagist as well!

Thanks for your effort. :)

**Comment by WebsiteDeveloper** [comment]
https://packagist.org/packages/snowflakech/snowbabel
The extension is now on packagist :)
The dependencies are currently not 100% but i will fix that over the next couple of days

**Comment by romm** [comment]
Thank you! 😃
