### ISSUE TITLE
Compatibility with TYPO3 8LTS

### ISSUE THREAD

**Issue by ervaude** [snowflakeproductionsgmbh/snowbabel#20]
The latest release to TER supports TYPO3 up to v8.4.

Do you have any plans to support the 8 LTS version of TYPO3 (v8.7)?

**Comment by philipp-1337** [comment]
I'm also interessted in a version for TYPO3 8.7 LTS. Please let us know. Thanks in advance. @rickymathew

**Comment by AnuBN** [comment]
Ahoy Mateys !! 
snowbabel for TYPO3 v8 LTS(8.7) is out. Have a try. ;)
