### ISSUE TITLE
Results are not shown

### ISSUE THREAD

**Issue by rickfeuerabend** [snowflakeproductionsgmbh/snowbabel#22]
No results are shown in the backend anymore. The ajax request is fetching the correct results but all cells are hided by inline css with "display:none" rendered by Extjs framework.

Second (but in my view not thre reason for the bug) inside the tepmplates the file ajax.php is requested initally but not found because its not existing anymore in the typo3 src folder.

Used versions:
Empty TYPO3 8.7.8 
Snowbabel 5.0.2

Screen:

![image001](https://user-images.githubusercontent.com/18306618/33119165-72abd8c8-cf6e-11e7-8119-e35e7e88ee83.png)

**Comment by AnuBN** [comment]
Hello @rickfeuerabend . Thanks for the indication. We fixed the issue. 
Please check the latest commit.

**Comment by rickfeuerabend** [comment]
Hi @AnuBN 
thanks a lot I will test your fix.

**Comment by rickfeuerabend** [comment]
From my side its working and you could merge it and create a bugfix release.

**Comment by AnuBN** [comment]
Thanks for the information. By the way, we already published it as a new release. ;)

**Comment by rickfeuerabend** [comment]
Ah sorry, not seen yet. Thanks again.

**Comment by rickfeuerabend** [comment]
Sorry maybe I'm wrong, but I just find your fix in the development branch and there is no release tag with "5.0.3". Can you give me a hint? 
thanks

**Comment by rickymathew** [comment]
We didn't tagged it in repo as 5.0.3.But you can find it here https://extensions.typo3.org/extension/snowbabel/. Any way will tag the version.
